<?php 
//本文件由前端工具生成，手动添加的配置可能会被覆盖 
return [
'css.layout-approve'            =>      '/assets/tenant/css/layout-approve.min.css', 
'css.layout-mobile'             =>      '/assets/tenant/css/layout-mobile.min.css', 
'css.umtang-tenant'             =>      '/assets/tenant/css/umtang-tenant.min.css', 
'css.umtang-tenant-mobile'      =>      '/assets/tenant/css/umtang-tenant-mobile.min.css', 
'js.activate'                   =>      '/assets/tenant/js/trade/activate.min.js', 
'js.album'                      =>      '/assets/tenant/js/shop/album.min.js', 
'js.approve-shop'               =>      '/assets/tenant/js/approve/approve-shop.min.js', 
'js.approve-tenant'             =>      '/assets/tenant/js/approve/approve-tenant.min.js', 
'js.encash'                     =>      '/assets/tenant/js/trade/encash.min.js', 
'js.encash-list'                =>      '/assets/tenant/js/trade/encash-list.min.js', 
'js.evaluate-detail'            =>      '/assets/tenant/js/evaluate/evaluate-detail.min.js', 
'js.evaluate-list'              =>      '/assets/tenant/js/evaluate/evaluate-list.min.js', 
'js.goods-info'                 =>      '/assets/tenant/js/goods/goods-info.min.js', 
'js.goods-list'                 =>      '/assets/tenant/js/goods/goods-list.min.js', 
'js.index'                      =>      '/assets/tenant/js/index/index.min.js', 
'js.notice'                     =>      '/assets/tenant/js/index/notice.min.js', 
'js.order'                      =>      '/assets/tenant/js/trade/order.min.js', 
'js.server'                     =>      '/assets/tenant/js/shop/server.min.js', 
'js.shop-apply'                 =>      '/assets/tenant/js/shop/shop-apply.min.js', 
'js.shop-cheap'                 =>      '/assets/tenant/js/shop/shop-cheap.min.js', 
'js.shop-info'                  =>      '/assets/tenant/js/shop/shop-info.min.js', 
'js.teacher'                    =>      '/assets/tenant/js/shop/teacher.min.js', 
'js.teacher-edit'               =>      '/assets/tenant/js/shop/teacher-edit.min.js', 
'tpl.activate'                  =>      '/assets/tenant/template/trade/activate.tpl', 
'tpl.album'                     =>      '/assets/tenant/template/shop/album.tpl', 
'tpl.approve-shop'              =>      '/assets/tenant/template/approve/approve-shop.tpl', 
'tpl.approve-tenant'            =>      '/assets/tenant/template/approve/approve-tenant.tpl', 
'tpl.encash'                    =>      '/assets/tenant/template/trade/encash.tpl', 
'tpl.encash-history'            =>      '/assets/tenant/template/trade/encash-history.tpl', 
'tpl.encash-order'              =>      '/assets/tenant/template/trade/encash-order.tpl', 
'tpl.evaluate-detail'           =>      '/assets/tenant/template/evaluate/evaluate-detail.tpl', 
'tpl.evaluate-list'             =>      '/assets/tenant/template/evaluate/evaluate-list.tpl', 
'tpl.goods-info'                =>      '/assets/tenant/template/goods/goods-info.tpl', 
'tpl.goods-list'                =>      '/assets/tenant/template/goods/goods-list.tpl', 
'tpl.index'                     =>      '/assets/tenant/template/index/index.tpl', 
'tpl.notice'                    =>      '/assets/tenant/template/index/notice.tpl', 
'tpl.order'                     =>      '/assets/tenant/template/trade/order.tpl', 
'tpl.server'                    =>      '/assets/tenant/template/shop/server.tpl', 
'tpl.shop-apply'                =>      '/assets/tenant/template/shop/shop-apply.tpl', 
'tpl.shop-cheap'                =>      '/assets/tenant/template/shop/shop-cheap.tpl', 
'tpl.shop-info'                 =>      '/assets/tenant/template/shop/shop-info.tpl', 
'tpl.teacher'                   =>      '/assets/tenant/template/shop/teacher.tpl', 
'tpl.teacher-edit'              =>      '/assets/tenant/template/shop/teacher-edit.tpl', 
];